In [1]:
import torch
import numpy

In [2]:
# Создаем тензор
x = torch.rand([3, 4])
x = torch.zeros([3, 4])
x = torch.ones([3, 4, 3])

print(x)
#x = torch.eye(3, 4)

x = torch.tensor(
[[1,  2,  3,  4],
 [5,  6,  7,  8],
 [9, 10, 11, 12]], dtype=torch.float32)

print(x, '<- tensor\n')
print(x.size(), '<- tensor size\n')
print(x.size(0), '<- dimension size\n')
print(x[1:, 1:3], '<- slicing support\n')

tensor([[[ 1.,  1.,  1.],
         [ 1.,  1.,  1.],
         [ 1.,  1.,  1.],
         [ 1.,  1.,  1.]],

        [[ 1.,  1.,  1.],
         [ 1.,  1.,  1.],
         [ 1.,  1.,  1.],
         [ 1.,  1.,  1.]],

        [[ 1.,  1.,  1.],
         [ 1.,  1.,  1.],
         [ 1.,  1.,  1.],
         [ 1.,  1.,  1.]]])
tensor([[  1.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]]) <- tensor

torch.Size([3, 4]) <- tensor size

3 <- dimension size

tensor([[  6.,   7.],
        [ 10.,  11.]]) <- slicing support



In [3]:
# Копирование (по ссылке и глубокое)
y = x

y[1, :] = 1
print(x, '\n', y, '<- shallow copy\n')

y = x.clone()
y[1, :] = 2
print(x, '\n', y, '<- deep copy')

tensor([[  1.,   2.,   3.,   4.],
        [  1.,   1.,   1.,   1.],
        [  9.,  10.,  11.,  12.]]) 
 tensor([[  1.,   2.,   3.,   4.],
        [  1.,   1.,   1.,   1.],
        [  9.,  10.,  11.,  12.]]) <- shallow copy

tensor([[  1.,   2.,   3.,   4.],
        [  1.,   1.,   1.,   1.],
        [  9.,  10.,  11.,  12.]]) 
 tensor([[  1.,   2.,   3.,   4.],
        [  2.,   2.,   2.,   2.],
        [  9.,  10.,  11.,  12.]]) <- deep copy


In [4]:
# Математические операции (стандартные поэлементные)
print(x + y, x * y, x / y, x - y,)
print(x % y, x**2, x**y, '<- basic math')

tensor([[  2.,   4.,   6.,   8.],
        [  3.,   3.,   3.,   3.],
        [ 18.,  20.,  22.,  24.]]) tensor([[   1.,    4.,    9.,   16.],
        [   2.,    2.,    2.,    2.],
        [  81.,  100.,  121.,  144.]]) tensor([[ 1.0000,  1.0000,  1.0000,  1.0000],
        [ 0.5000,  0.5000,  0.5000,  0.5000],
        [ 1.0000,  1.0000,  1.0000,  1.0000]]) tensor([[ 0.,  0.,  0.,  0.],
        [-1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.]])
tensor([[ 0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.]]) tensor([[   1.,    4.,    9.,   16.],
        [   1.,    1.,    1.,    1.],
        [  81.,  100.,  121.,  144.]]) tensor([[ 1.0000e+00,  4.0000e+00,  2.7000e+01,  2.5600e+02],
        [ 1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00],
        [ 3.8742e+08,  1.0000e+10,  2.8531e+11,  8.9161e+12]]) <- basic math


In [5]:
# Более сложные операции
print(torch.exp(x))
print(torch.log(x))
print(torch.sin(x))

tensor([[ 2.7183e+00,  7.3891e+00,  2.0086e+01,  5.4598e+01],
        [ 2.7183e+00,  2.7183e+00,  2.7183e+00,  2.7183e+00],
        [ 8.1031e+03,  2.2026e+04,  5.9874e+04,  1.6275e+05]])
tensor([[ 0.0000,  0.6931,  1.0986,  1.3863],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 2.1972,  2.3026,  2.3979,  2.4849]])
tensor([[ 0.8415,  0.9093,  0.1411, -0.7568],
        [ 0.8415,  0.8415,  0.8415,  0.8415],
        [ 0.4121, -0.5440, -1.0000, -0.5366]])


In [6]:
# Логические операции
y = x[x > 3]
print(y)
y = (x > 3)
print(y)

tensor([  4.,   9.,  10.,  11.,  12.])
tensor([[ 0,  0,  0,  1],
        [ 0,  0,  0,  0],
        [ 1,  1,  1,  1]], dtype=torch.uint8)


In [7]:
# Переопределение типа
x = x.float()
print(x)
x = x.double()
print(x)
x = x.int()
print(x)
x = x.float()

tensor([[  1.,   2.,   3.,   4.],
        [  1.,   1.,   1.,   1.],
        [  9.,  10.,  11.,  12.]])
tensor([[  1.,   2.,   3.,   4.],
        [  1.,   1.,   1.,   1.],
        [  9.,  10.,  11.,  12.]], dtype=torch.float64)
tensor([[  1,   2,   3,   4],
        [  1,   1,   1,   1],
        [  9,  10,  11,  12]], dtype=torch.int32)


In [8]:
# Взаимодействие с Numpy
x = numpy.array([[1, 2, 3, 4], [4, 3, 2, 1]])
print(x)
x = torch.from_numpy(x)
print(x)
x = x.numpy()
print(x)
x = torch.from_numpy(x).float().int().double()
print(x)

[[1 2 3 4]
 [4 3 2 1]]
tensor([[ 1,  2,  3,  4],
        [ 4,  3,  2,  1]])
[[1 2 3 4]
 [4 3 2 1]]
tensor([[ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]], dtype=torch.float64)


In [9]:
# Перемещение на GPU
import time
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print(device, 'is avaliable')
x_cuda = x.to(device)
print(x_cuda, '<- CUDA Tensor!')
print(x)

cuda:0 is avaliable
tensor([[ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]], dtype=torch.float64, device='cuda:0') <- CUDA Tensor!
tensor([[ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]], dtype=torch.float64)


In [10]:
# CPU time
%time y = (x - x + x*10.0) ** 2

CPU times: user 127 µs, sys: 41 µs, total: 168 µs
Wall time: 224 µs


In [11]:
# GPU time
%time y_cuda = (x_cuda - x_cuda + x_cuda * 10.0) ** 2

CPU times: user 659 µs, sys: 0 ns, total: 659 µs
Wall time: 403 µs


In [12]:
# Автоматическое (символьное) дифференциирование (обратное распространение градиента) (случай скаляра)
import torch.autograd

x = torch.tensor(
    [[1,  2,  3,  4],
     [5,  6,  7,  8],
     [9, 10, 11, 12]], requires_grad=True)

formula = (x ** 2).sum().median()
formula.backward()

print(x.grad, '<- gradient')

tensor([[  2,   4,   6,   8],
        [ 10,  12,  14,  16],
        [ 18,  20,  22,  24]]) <- gradient


In [13]:
# Как тензор хранит свою историю
print(formula.grad_fn)
print(formula.grad_fn.next_functions[0][0])
print(formula.grad_fn.next_functions[0][0].next_functions[0][0])
print(formula.grad_fn.next_functions[0][0].next_functions[0][0].next_functions[0][0])

## Задание 1
Написать и вычислить бинарную кросс-энтопию для векторов target и probs при помощи средств pytorch.
Бинарная кросс-энтропия вычисляется:

$$BCE(t, p) = - \sum_i t_i \log(p_i) + (1 - t_i) \log(1 - p_i)$$

target = (0, 0, 0, 0, 1, 1, 1, 1)
probs = (0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8)

Какой из элементов суммы дает наибольший вклад в функцию потерь?

In [14]:
target = torch.tensor([0, 0, 0, 0, 1, 1, 1, 1], requires_grad=True) 
probs = torch.tensor([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8], requires_grad=True)

def bce(t, p):
    return - ((torch.log(p[t == 1]).sum() + (torch.log(1 - p[t == 0]).sum())))
bce(target, probs)

tensor(2.9798)

# Задание 2

Логистическая регрессия минимизирует функцию бинарной кросс-энтропии (BCE), предполагая, что
$$p_i = \sigma (< w_i, x_i >)$$
где $w_i$ -- веса свойств объектов, $x_i$ -- свойства объектов. Пусть $\vec{x} = (1, x_1, x_2)$. Подставить вероятности в выражение $BCE$ и найти производную $BCE$ по весам.
Вычислить производную в случае двух объектов (любым способом, можно посчитать руками, можно написать скрипт):

$t = 1, x = (1, 1, 1)$

$t = 0, x = (1, 0, 1)$

В точке w = (0, 0, 0).

Совпадает ли результат явного вычисления с результатом работы функции backward?

In [15]:
def sigmoid(w, x):
    scalar = -x @ w.transpose(-1,0)
    return 1 / (1 + torch.exp(scalar) + 1e-10)

w = torch.tensor([0,0,0], requires_grad=True, dtype=torch.float32)
x = torch.tensor([[1,1,1],[1,0,1]], dtype=torch.float32)


probs = sigmoid(w,x)
print(probs)
f = bce(torch.tensor([1,0]), probs)
f.backward()
print(f, w.grad)

tensor([ 0.5000,  0.5000])
tensor(1.3863) tensor([ 0.0000, -0.5000,  0.0000])


## Задание 3

Средствами pytorch реализовать алгоритм градиентного спуска.

При помощи этого алгоритма найти минимум функций:
$x^2 + y^2$ с начальным приближением $x_0 = 10, y_0 = 5$, 

$0.5 \log x + 0.5 \log (1 - x)$ с начальным приближением $x_0 = 0.9$, 

$x^2 + 10 y^2 + 2xy$, с начальным приближением $x_0 = 10.0, y_0 = 10.0$

In [124]:
def GD(f, x, y, alpha=torch.tensor(1e-1)):
    for i in range(30000):
        f.backward(retain_graph=True)
        x.data.sub_(alpha * x.grad)
        y.data.sub_(alpha * y.grad)
        x.grad = torch.tensor(0, dtype=torch.float32)
        y.grad = torch.tensor(0, dtype=torch.float32)
    return x, y

In [125]:
x = torch.tensor(10, requires_grad=True, dtype=torch.float32)
y = torch.tensor(5, requires_grad=True, dtype=torch.float32)

f = x**2 + y**2

print(GD(f, x, y))

(tensor(1.00000e-45 *
       2.8026), tensor(1.00000e-45 *
       2.8026))


In [126]:
x = torch.tensor(0.9, requires_grad=True, dtype=torch.float32)

f = 0.5*torch.log(x) + 0.5*torch.log(1-x)

print(GD(f, x, y))

(tensor(15000.1553), tensor(1.00000e-45 *
       2.8026))


In [127]:
x = torch.tensor(10, requires_grad=True, dtype=torch.float32)
y = torch.tensor(10, requires_grad=True, dtype=torch.float32)

f = x**2 + 10*y**2 + 2*x*y

print(GD(f, x, y))

(tensor(2.2222), tensor(10.))


## Задание 4


При помощи алгоритма градиентного спуска оптимизировать вектор probs при фиксированном векторе target из задания 1.
Рассмотреть два варианта решения задачи: 

1) при помощи CPU 

2) при помощи GPU

Получилось ли ускорить процесс при помощи GPU? Обсудить, почему.

In [77]:
def sigmoid(w, x):
    scalar = -x @ w.transpose(-1,0)
    return 1 / (1 + torch.exp(scalar) + 1e-10)

In [78]:
def GD(f, x, alpha=torch.tensor(0.005, dtype=torch.float32, device=device)):
    for i in range(10000):
        f.backward(retain_graph=True)
        x.data.sub_(alpha * x.grad.data)
        x.grad = torch.zeros(x.size(), dtype=torch.float32, device=device)
    return x

def bce(t, p):
    return - ((torch.log(p[t == 1]).sum() + (torch.log(1 - p[t == 0]).sum())))

О градиентном спуске:
https://ru.wikipedia.org/wiki/%D0%93%D1%80%D0%B0%D0%B4%D0%B8%D0%B5%D0%BD%D1%82%D0%BD%D1%8B%D0%B9_%D1%81%D0%BF%D1%83%D1%81%D0%BA

In [79]:
target = torch.tensor([0, 0, 0, 0, 1, 1, 1, 1], dtype=torch.float32, device=device) 
probs = torch.tensor([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8], dtype=torch.float32, requires_grad=True, device=device)

f = bce(target, probs)
print(GD(f, probs))

tensor([ -55.4509,  -62.2940,  -71.1196,  -82.9351,  100.5031,   83.9349,
          72.1194,   63.2937], device='cuda:0')
